name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  web-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git status
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --target web
    - run: echo ${{ github.event.release }}
    - run: echo ${{ github.event }}
    - run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/json" \
          --hostname HOSTNAME \
          ${{ github.event.release.upload_url }}?name=package.json \
          -f "@pkg/package.json"