name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  web-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git status
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/package.json
        asset_name: package.json
        asset_content_type: application/json
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/tampermonky_wasm.d.ts
        asset_name: tampermonky_wasm.d.ts
        asset_content_type: text/javascript
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/tampermonky_wasm.js
        asset_name: tampermonky_wasm.js
        asset_content_type: text/javascript
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/tampermonky_wasm_bg.wasm
        asset_name: tampermonky_wasm_bg.wasm
        asset_content_type: application/wasm
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pkg/tampermonky_wasm_bg.wasm.d.ts
        asset_name: tampermonky_wasm_bg.wasm.d.ts
        asset_content_type: text/javascript
