name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release package
      run: cargo build --release

  web-pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install wasm-pack
      run: cargo install wasm-pack
    - name: Build
      run: wasm-pack build --target no-modules